import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Caudex } from "next/font/google";
import { Archivo } from "next/font/google";

const caudex = Caudex({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-caudex",
  weight: "400",
});
const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + caudex.variable + archivo.variable}>
        {children}
      </body>
    </html>
  );
}
