/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYJfOGchCMX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"

export function Profile2() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="sticky top-0 hidden h-screen w-[300px] flex-col items-center justify-between bg-gradient-to-br from-[#6366F1] to-[#9333EA] p-8 text-white lg:flex">
        <div className="space-y-6">
          <div className="flex flex-col items-center space-y-4">
            <Avatar size="xl">
              <AvatarImage alt="Profile Picture" src="/profile.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="text-center">
              <h2 className="text-2xl font-bold">John Doe</h2>
              <p className="text-gray-300">Software Engineer</p>
            </div>
          </div>
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <MailIcon className="h-5 w-5" />
              <span>john@example.com</span>
            </div>
            <div className="flex items-center space-x-2">
              <PhoneIcon className="h-5 w-5" />
              <span>+1 (555) 123-4567</span>
            </div>
            <div className="flex items-center space-x-2">
              <LocateIcon className="h-5 w-5" />
              <span>New York, NY</span>
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <Link
            className="inline-flex items-center justify-center rounded-md bg-white/10 px-4 py-2 text-sm font-medium text-white hover:bg-white/20 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75"
            href="#"
          >
            <DownloadIcon className="mr-2 h-5 w-5" />
            Download CV
          </Link>
          <div className="flex space-x-4">
            <Link className="text-white hover:text-gray-300" href="#">
              <LinkedinIcon className="h-6 w-6" />
            </Link>
            <Link className="text-white hover:text-gray-300" href="#">
              <GithubIcon className="h-6 w-6" />
            </Link>
            <Link className="text-white hover:text-gray-300" href="#">
              <TwitterIcon className="h-6 w-6" />
            </Link>
          </div>
        </div>
      </div>
      <div className="flex-1 bg-gray-100 dark:bg-gray-900 p-8 lg:p-12">
        <div className="grid gap-12">
          <div>
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-2xl font-bold">Projects</h2>
              <Link
                className="inline-flex items-center rounded-md bg-gradient-to-r from-[#6366F1] to-[#9333EA] px-4 py-2 text-sm font-medium text-white hover:from-[#4F46E5] hover:to-[#7E22CE] focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75"
                href="#"
              >
                <PlusIcon className="mr-2 h-5 w-5" />
                Add Project
              </Link>
            </div>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-md bg-white p-4 shadow-md dark:bg-gray-800 dark:text-gray-200">
                <div className="mb-4">
                  <img
                    alt="Project Thumbnail"
                    className="h-auto w-full rounded-md object-cover"
                    height={225}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/225",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                </div>
                <h3 className="mb-2 text-lg font-bold">Project Name</h3>
                <p className="mb-4 text-gray-500 dark:text-gray-400">A brief description of the project.</p>
                <div className="flex items-center justify-between">
                  <div className="flex space-x-2">
                    <Badge>React</Badge>
                    <Badge>Tailwind CSS</Badge>
                  </div>
                  <Link
                    className="inline-flex items-center rounded-md bg-gradient-to-r from-[#6366F1] to-[#9333EA] px-3 py-1 text-sm font-medium text-white hover:from-[#4F46E5] hover:to-[#7E22CE] focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75"
                    href="#"
                  >
                    <ArrowRightIcon className="mr-2 h-4 w-4" />
                    View
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h2 className="mb-6 text-2xl font-bold">Experience</h2>
            <div className="space-y-8">
              <div>
                <h3 className="mb-2 text-lg font-bold">Software Engineer</h3>
                <p className="mb-2 text-gray-500 dark:text-gray-400">Acme Inc. | Jan 2020 - Present</p>
                <p className="text-gray-700 dark:text-gray-300">
                  Developed and maintained web applications using React, Node.js, and MongoDB. Collaborated with
                  cross-functional teams to deliver high-quality software solutions.
                </p>
              </div>
            </div>
          </div>
          <div>
            <h2 className="mb-6 text-2xl font-bold">Education</h2>
            <div className="space-y-8">
              <div>
                <h3 className="mb-2 text-lg font-bold">Bachelor of Science in Computer Science</h3>
                <p className="mb-2 text-gray-500 dark:text-gray-400">University of Example | 2016 - 2020</p>
                <p className="text-gray-700 dark:text-gray-300">
                  Graduated with a GPA of 3.8 and received the Dean's List award.
                </p>
              </div>
            </div>
          </div>
          <div>
            <h2 className="mb-6 text-2xl font-bold">Certifications</h2>
            <div className="space-y-8">
              <div>
                <h3 className="mb-2 text-lg font-bold">AWS Certified Solutions Architect - Associate</h3>
                <p className="mb-2 text-gray-500 dark:text-gray-400">Amazon Web Services | Issued May 2021</p>
                <p className="text-gray-700 dark:text-gray-300">
                  Demonstrated expertise in designing and deploying scalable, highly available, and fault-tolerant
                  systems on AWS.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function DownloadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function LocateIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
