/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QeJFSxbySpL
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { CardContent, Card } from "@/components/ui/card";
import Image from "next/image";
import { JSX, SVGProps } from "react";

export function Profile1() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="sticky top-0 hidden h-screen w-[280px] flex-col border-r bg-gray-100 p-6 dark:border-gray-800 dark:bg-gray-800 lg:flex">
        <div className="flex flex-col items-center space-y-6">
          <Image
            alt="Profile Picture"
            className="rounded-full"
            height={120}
            src="/placeholder.svg"
            style={{
              aspectRatio: "120/120",
              objectFit: "cover",
            }}
            width={120}
          />
          <div className="space-y-2 text-center">
            <h2 className="text-2xl font-bold">John Doe</h2>
            <p className="text-gray-500 dark:text-gray-400">
              Software Engineer
            </p>
          </div>
          <div className="flex w-full flex-col items-start space-y-2 text-sm font-medium text-gray-500 dark:text-gray-400">
            <div className="flex items-center gap-2">
              <LocateIcon className="h-4 w-4" />
              <span>San Francisco, CA</span>
            </div>
            <div className="flex items-center gap-2">
              <MailboxIcon className="h-4 w-4" />
              <span>john@example.com</span>
            </div>
            <div className="flex items-center gap-2">
              <PhoneIcon className="h-4 w-4" />
              <span>+1 (555) 123-4567</span>
            </div>
          </div>
        </div>
      </div>
      <div className="flex-1 space-y-8 p-6 lg:p-12">
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-2xl font-bold">Projects</h3>
            <Link
              className="text-sm font-medium text-indigo-500 hover:underline"
              href="#"
            >
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="text-lg font-semibold">Project A</h4>
                  <Badge variant="default">Completed</Badge>
                </div>
                <p className="text-gray-500 dark:text-gray-400">
                  A brief description of Project A.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2 text-sm font-medium text-gray-500 dark:text-gray-400">
                    <CalendarDaysIcon className="h-4 w-4" />
                    <span>Jan 2022 - Jun 2022</span>
                  </div>
                  <Link className="text-indigo-500 hover:underline" href="#">
                    View
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="text-lg font-semibold">Project B</h4>
                  <Badge variant="destructive">In Progress</Badge>
                </div>
                <p className="text-gray-500 dark:text-gray-400">
                  A brief description of Project B.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2 text-sm font-medium text-gray-500 dark:text-gray-400">
                    <CalendarDaysIcon className="h-4 w-4" />
                    <span>Jul 2022 - Present</span>
                  </div>
                  <Link className="text-indigo-500 hover:underline" href="#">
                    View
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="text-lg font-semibold">Project C</h4>
                  <Badge variant="destructive">Cancelled</Badge>
                </div>
                <p className="text-gray-500 dark:text-gray-400">
                  A brief description of Project C.
                </p>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2 text-sm font-medium text-gray-500 dark:text-gray-400">
                    <CalendarDaysIcon className="h-4 w-4" />
                    <span>Aug 2021 - Dec 2021</span>
                  </div>
                  <Link className="text-indigo-500 hover:underline" href="#">
                    View
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div>
          <h3 className="mb-4 text-2xl font-bold">Experience</h3>
          <div className="space-y-6">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-indigo-500 to-purple-500 p-2 text-white">
                  <BriefcaseIcon className="h-full w-full" />
                </div>
              </div>
              <div>
                <h4 className="text-lg font-semibold">Software Engineer</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  Acme Inc. | Jan 2020 - Present
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Developed and maintained web applications using React,
                  Node.js, and other modern technologies.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-green-500 to-yellow-500 p-2 text-white">
                  <BriefcaseIcon className="h-full w-full" />
                </div>
              </div>
              <div>
                <h4 className="text-lg font-semibold">Intern</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  Globex Corporation | Jun 2019 - Aug 2019
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Assisted the engineering team in developing and testing new
                  features.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div>
          <h3 className="mb-4 text-2xl font-bold">Education</h3>
          <div className="space-y-6">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-blue-500 to-cyan-500 p-2 text-white">
                  <GraduationCapIcon className="h-full w-full" />
                </div>
              </div>
              <div>
                <h4 className="text-lg font-semibold">
                  Bachelor of Science in Computer Science
                </h4>
                <p className="text-gray-500 dark:text-gray-400">
                  University of California, Berkeley | 2015 - 2019
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Graduated with Honors
                </p>
              </div>
            </div>
          </div>
        </div>
        <div>
          <h3 className="mb-4 text-2xl font-bold">Certifications</h3>
          <div className="space-y-6">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-orange-500 to-red-500 p-2 text-white">
                  <AwardIcon className="h-full w-full" />
                </div>
              </div>
              <div>
                <h4 className="text-lg font-semibold">
                  AWS Certified Solutions Architect - Associate
                </h4>
                <p className="text-gray-500 dark:text-gray-400">
                  Amazon Web Services | Issued May 2021
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-pink-500 to-purple-500 p-2 text-white">
                  <AwardIcon className="h-full w-full" />
                </div>
              </div>
              <div>
                <h4 className="text-lg font-semibold">
                  Google Cloud Certified Professional Data Engineer
                </h4>
                <p className="text-gray-500 dark:text-gray-400">
                  Google Cloud | Issued September 2022
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function AwardIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  );
}

function BriefcaseIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  );
}

function CalendarDaysIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}

function GraduationCapIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>,
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 10v6M2 10l10-5 10 5-10 5z" />
      <path d="M6 12v5c3 3 9 3 12 0v-5" />
    </svg>
  );
}

function LocateIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  );
}

function MailboxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  );
}

function PhoneIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}
